package FirefoxBrowser;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NewAppointmentTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	driver = new FirefoxDriver();;
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void newAppointment() throws InterruptedException {
    driver.get("https://batteriesplus-uat.repairq.io/site/login");
    driver.manage().window().setSize(new Dimension(1280, 1024));
    
    
    WebElement usernameField = driver.findElement(By.id("UserLoginForm_username"));
    usernameField.click();
    usernameField.clear();
    usernameField.sendKeys("l.costa@cinq.com.br");
    
    WebElement passwordField = driver.findElement(By.id("UserLoginForm_password"));
    passwordField.click();
    passwordField.clear();
    passwordField.sendKeys("123");
    
    driver.findElement(By.id("UserLoginForm_password")).click();
    driver.findElement(By.id("UserLoginForm_password")).click();
    
    driver.findElement(By.cssSelector(".btn-new")).click();
    driver.findElement(By.linkText("Check In")).click();
    Thread.sleep(5000);
    driver.findElement(By.xpath("//*[@id=\"ticketCheckin\"]/div[2]/div/a[1]/div")).click();
    Thread.sleep(5000);
    driver.findElement(By.xpath("//*[@id=\"appointmentModal\"]/div[3]/a")).click();
    Thread.sleep(5000);
    driver.findElement(By.linkText("+")).click();
    Thread.sleep(5000);
    driver.findElement(By.id("apt_customer")).click();
    driver.findElement(By.id("apt_customer")).sendKeys("lucas");
    Thread.sleep(10000);
    driver.findElement(By.id("apt_customer")).click();
    driver.findElement(By.id("apt_customer")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("apt_customer")).sendKeys("lucas");
    driver.findElement(By.id("apt_customer")).sendKeys(Keys.ENTER);
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".add-on > .icon-calendar")).click();
    driver.findElement(By.linkText("24")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".btn-save")).click();
    Thread.sleep(5000);
    
  }
  }
  
