// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ContactnotifyTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void contactnotify() {
    driver.get("https://batteriesplus-uat.repairq.io/ticket/8028");
    driver.manage().window().setSize(new Dimension(1176, 743));
    driver.findElement(By.linkText("Next: Contact Customer")).click();
    driver.findElement(By.id("claim-contact-notify-note")).click();
    driver.findElement(By.id("claim-contact-notify-note")).sendKeys("12");
    driver.findElement(By.linkText("Contact Notified")).click();
    driver.findElement(By.linkText("Next: Send To RMS")).click();
    driver.findElement(By.linkText("Send to RMS")).click();
  }
}
