// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateEstimateTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createEstimate() {
    driver.get("https://batteriesplus-uat.repairq.io/ticket/edit/5860");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("addBtn")).click();
    driver.findElement(By.cssSelector(".catalogItem-select:nth-child(8) > .item-name")).click();
    driver.findElement(By.cssSelector(".submit-button")).click();
    driver.findElement(By.linkText("Create Estimate")).click();
    driver.findElement(By.linkText("Continue")).click();
    driver.findElement(By.cssSelector(".add-on > .icon-calendar")).click();
    driver.findElement(By.cssSelector(".ui-icon-circle-triangle-e")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ui-icon-circle-triangle-e"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("4")).click();
    driver.findElement(By.linkText("Continue")).click();
    driver.findElement(By.cssSelector(".check")).click();
    driver.findElement(By.linkText("Continue")).click();
    driver.findElement(By.linkText("Start Repair")).click();
    driver.findElement(By.linkText("Repair Complete")).click();
    driver.findElement(By.linkText("Confirm Estimate")).click();
  }
}
