// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FieldtestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void fieldtest() {
    driver.get("https://batteriesplus-uat.repairq.io/ticket/claim?serviceProgramId=1");
    driver.manage().window().setSize(new Dimension(1120, 646));
    driver.findElement(By.id("customerSearch")).click();
    driver.findElement(By.id("customerSearch")).sendKeys("lucas");
    driver.findElement(By.id("ui-active-menuitem")).click();
    {
      WebElement element = driver.findElement(By.id("ui-active-menuitem"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Dismiss")).click();
    driver.findElement(By.linkText("Continue with Claim")).click();
    {
      WebElement element = driver.findElement(By.linkText("Continue with Claim"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".check")).click();
    driver.findElement(By.linkText("Continue")).click();
    driver.findElement(By.cssSelector(".category-flex > .category-select:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".category-select:nth-child(12)")).click();
    driver.findElement(By.cssSelector(".catalogItem-select:nth-child(15) > .item-name")).click();
    js.executeScript("window.scrollTo(0,1056)");
    driver.findElement(By.id("claim-device-serial")).click();
    driver.findElement(By.id("claim-device-serial")).sendKeys("12");
    driver.findElement(By.id("claim-device-serial")).sendKeys(Keys.ENTER);
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector("p")).click();
    {
      WebElement element = driver.findElement(By.id("tinymce"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>lasldlals</p>'}", element);
    }
    driver.switchTo().defaultContent();
    driver.findElement(By.linkText("Save & Submit")).click();
    driver.findElement(By.name("87")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(4) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(6) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(10) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(14) .radio-inline:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(15) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(17) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(19) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(21) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(23) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(29) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(30) .radio-inline:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(33) .radio-inline:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(34) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(38) .radio-inline:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(41) .radio-inline:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(42) .radio-inline:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(43) .radio-inline:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(45) .radio-inline:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(46) .radio-inline:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(47) .radio-inline:nth-child(2)")).click();
    driver.findElement(By.id("customField_80")).click();
    driver.findElement(By.id("customField_80")).sendKeys("test");
    driver.findElement(By.linkText("Save & Submit")).click();
    driver.findElement(By.cssSelector(".error .radio-inline:nth-child(3)")).click();
    driver.findElement(By.linkText("Save & Submit")).click();
    {
      WebElement element = driver.findElement(By.linkText("Save & Submit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Continue with Claim")).click();
  }
}
