// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InspectionReportTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void inspectionReport() {
    driver.get("https://batteriesplus-uat.repairq.io/ticket/edit/7578");
    driver.manage().window().setSize(new Dimension(1176, 743));
    driver.findElement(By.cssSelector(".control-group:nth-child(2) .radio-inline:nth-child(3) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(7) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(9) .radio-inline:nth-child(3) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(11) .radio-inline:nth-child(3) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(12) .radio-inline:nth-child(4) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(13) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(24) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(25) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(27) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(28) .radio-inline:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(32) .radio-inline:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(36) .radio-inline:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(39) .radio-inline:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(40) .radio-inline:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(43) .radio-inline:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(45) .radio-inline:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(46) .radio-inline:nth-child(2)")).click();
    driver.findElement(By.id("customField_80")).click();
    driver.findElement(By.id("customField_80")).sendKeys("ok");
    driver.findElement(By.linkText("Save & Submit")).click();
    driver.findElement(By.id("addBtn")).click();
    driver.findElement(By.cssSelector(".catalogItem-select:nth-child(5) > .item-name")).click();
    driver.findElement(By.cssSelector(".btn-large")).click();
    driver.findElement(By.linkText("Create Estimate")).click();
    driver.findElement(By.linkText("Continue")).click();
    driver.findElement(By.cssSelector(".add-on > .icon-calendar")).click();
    driver.findElement(By.linkText("30")).click();
    driver.findElement(By.linkText("Continue")).click();
    driver.findElement(By.cssSelector(".check")).click();
    driver.findElement(By.linkText("Continue")).click();
    driver.findElement(By.linkText("Start Repair")).click();
    driver.findElement(By.linkText("Repair Complete")).click();
    driver.findElement(By.linkText("Confirm Estimate")).click();
  }
}
