// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class StartNewTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void startNew() throws InterruptedException {
    driver.get("https://batteriesplus-uat.repairq.io/site/login");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("UserLoginForm_username")).click();
    driver.findElement(By.id("UserLoginForm_username")).sendKeys("l.costa@cinq.com.br");
    driver.findElement(By.id("UserLoginForm_password")).click();
    driver.findElement(By.id("UserLoginForm_password")).sendKeys("123");
    driver.findElement(By.cssSelector(".btn-new")).click();
    driver.findElement(By.linkText("Check In")).click();
    Thread.sleep(5000);
    driver.findElement(By.xpath("//div[@id=\'ticketCheckin\']/div[2]/div/a[5]/div")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".service-auth-select:nth-child(1) > .image-container")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector("#serviceProgram div:nth-child(2) > .image-container")).click();
    Thread.sleep(5000);
    driver.findElement(By.id("customerSearch")).click();
    Thread.sleep(5000);
    Thread.sleep(5000);
    driver.findElement(By.id("customerSearch")).sendKeys("lucas");
    Thread.sleep(10000);
    driver.findElement(By.xpath("//*[@id=\"customer-search-modal\"]/ul/li[1]/a")).click();
    Thread.sleep(5000);
   
    {
      Thread.sleep(5000);
     
      driver.findElement(By.linkText("Dismiss")).click();
   }
    
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".btn-primary > .icon-ok")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".check")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".btn-primary > .icon-ok")).click();
    Thread.sleep(45000);
    driver.findElement(By.xpath("//*[@id=\"new-device-form\"]/fieldset/div[1]/div[2]/div/div/div/div[1]")).click();
    Thread.sleep(5000);
    driver.findElement(By.xpath("//*[@id=\"new-device-form\"]/fieldset/div[1]/div[2]/div/div/div/div[12]")).click();
    Thread.sleep(5000);
    driver.findElement(By.xpath("//*[@id=\"new-device-form\"]/fieldset/div[1]/div[2]/div/div/div/div[14]")).click();
    Thread.sleep(5000);
    driver.findElement(By.id("claim-device-serial")).sendKeys("123456");
    Thread.sleep(5000);
    driver.findElement(By.id("claim-device-serial")).sendKeys(Keys.ENTER);
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector("p")).click();
    {
      WebElement element = driver.findElement(By.id("tinymce"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'testing'}", element);
    }
    driver.switchTo().defaultContent();
    driver.findElement(By.linkText("Continue with Claim")).click();
    Thread.sleep(10000);
    driver.findElement(By.linkText("Save & Submit")).click();
    Thread.sleep(10000);
    driver.findElement(By.name("87")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(4) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(6) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(10) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(14) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(15) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(17) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(19) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(21) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(23) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(29) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(30) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(33) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(34) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(38) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(41) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(42) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(43) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(45) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(46) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(47) .radio-inline:nth-child(2) > .required")).click();
    driver.findElement(By.id("customField_80")).click();
    driver.findElement(By.id("customField_80")).sendKeys("testing");
    driver.findElement(By.linkText("Save & Submit")).click();
    Thread.sleep(10000);
    driver.findElement(By.id("addBtn")).click();
    Thread.sleep(10000);
    driver.findElement(By.xpath("//*[@id=\"ticket-item-form\"]/fieldset/div[2]/div[2]/div/div/div/div[8]")).click();
    Thread.sleep(5000);
    driver.findElement(By.xpath("//*[@id=\"ticket-item-form\"]/fieldset/div[3]/input[2]")).click();
    Thread.sleep(5000);
    driver.findElement(By.linkText("Create Estimate")).click();
    Thread.sleep(10000);
    driver.findElement(By.linkText("Continue")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".add-on > .icon-calendar")).click();
    driver.findElement(By.xpath("//*[@id=\"claim-walkthrough-modal\"]/div[3]/a[2]")).click();
    Thread.sleep(5000);
  
    {
      WebElement element = driver.findElement(By.cssSelector(".ui-icon-circle-triangle-e"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    
    }
    driver.findElement(By.linkText("4")).click();
    driver.findElement(By.linkText("Continue")).click();
    driver.findElement(By.cssSelector(".check")).click();
    driver.findElement(By.linkText("Continue")).click();
    driver.findElement(By.linkText("Start Repair")).click();
    driver.findElement(By.linkText("Repair Complete")).click();
    driver.findElement(By.linkText("Confirm Estimate")).click();
  }
 }
