package batteriesplus;

// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class CustomerSearch {

	
	public void customerSearchChrome() throws InterruptedException {
		customerSearch(new ChromeDriver());
	}
	
	@Test
	public void customerSearchFirefox() throws InterruptedException {
		customerSearch(new FirefoxDriver());
	}
	
	
	public void customerSearchIE() throws InterruptedException {
		customerSearch(new InternetExplorerDriver());
	}
	
	private void customerSearch(WebDriver driver) throws InterruptedException {
		driver.get("https://batteriesplus-uat.repairq.io/site/login");
		driver.manage().window().setSize(new Dimension(1176, 743));

		WebElement usernameField = driver.findElement(By.id("UserLoginForm_username"));
		usernameField.click();
		usernameField.clear();
		usernameField.sendKeys("l.costa@cinq.com.br");

		WebElement passwordField = driver.findElement(By.id("UserLoginForm_password"));
		passwordField.click();
		passwordField.clear();
		passwordField.sendKeys("123");

		driver.findElement(By.id("UserLoginForm_password")).click();
		driver.findElement(By.id("UserLoginForm_password")).click();
		driver.findElement(By.cssSelector(".btn-new")).click();
		driver.findElement(By.linkText("Check In")).click();
		Thread.sleep(5000);
		driver.findElement(By.cssSelector("#ticketCheckin [href='#customerSearchModal']")).click();
		Thread.sleep(5000);
		driver.findElement(By.id("customerSearchModalInput")).click();
		driver.findElement(By.id("customerSearchModalInput")).sendKeys(Keys.DOWN);
		driver.findElement(By.id("customerSearchModalInput")).sendKeys("pozzi");
		driver.findElement(By.id("customerSearchModalInput")).sendKeys(Keys.ENTER);
		Thread.sleep(10000);
		
		driver.quit();
	}
}
