package batteriesplus;

// Generated by Selenium IDE
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;

import repairq.RepairQTest;

public class LoginRepairTest extends RepairQTest {

	@Test
	public void loginrepairChrome() throws InterruptedException {
		loginrepair();
	}

	public void loginrepairFirefox() throws InterruptedException {
		loginrepair();
	}

	public void loginrepairIE() throws InterruptedException {
		loginrepair();
	}


	// test login fail
	public void WrongLoginChrome() throws InterruptedException {
		WrongLogin(new ChromeDriver());
	}

	public void WrongLoginFirefo() throws InterruptedException {
		WrongLogin(new ChromeDriver());
	}
			
	public void WrongLoginIE() throws InterruptedException {
		WrongLogin(new ChromeDriver());
	}

	private void loginrepair() throws InterruptedException {
		this.rqLogin("admin", "outono123");
		Assertions.assertFalse(driver.getCurrentUrl().equals(this.getLoginUrl()));
	}

	private void WrongLogin(WebDriver driver) throws InterruptedException {

		driver.get("http://lucas.rq.test/site/login");
		driver.manage().window().setSize(new Dimension(1176, 743));

		WebElement usernameField = driver.findElement(By.id("UserLoginForm_username"));
		usernameField.click();
		usernameField.clear();
		usernameField.sendKeys("admin");

		WebElement passwordField = driver.findElement(By.id("UserLoginForm_password"));
		passwordField.click();
		passwordField.clear();
		passwordField.sendKeys("outono123");

		driver.findElement(By.id("UserLoginForm_password")).click();
		driver.findElement(By.id("UserLoginForm_password")).click();
		driver.findElement(By.cssSelector(".btn-new")).click();

	}

}
