package batteriesplus;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;



public class NewAppointment {

	@Test
	public void newAppointmentChrome() throws InterruptedException {
		newappointment(new ChromeDriver());
	}

	@Test
	public void newAppointmentFirefox() throws InterruptedException {
		newappointment(new FirefoxDriver());
	}

	@Test
	public void newAppointmentIE() throws InterruptedException {
		newappointment(new InternetExplorerDriver());
	}

	private void newappointment(WebDriver driver) throws InterruptedException {
		driver.get("https://batteriesplus-uat.repairq.io/site/login");
		driver.manage().window().setSize(new Dimension(1176, 743));
  
    
    
    WebElement usernameField = driver.findElement(By.id("UserLoginForm_username"));
    usernameField.click();
    usernameField.clear();
    usernameField.sendKeys("l.costa@cinq.com.br");
    
    WebElement passwordField = driver.findElement(By.id("UserLoginForm_password"));
    passwordField.click();
    passwordField.clear();
    passwordField.sendKeys("123");
    
    driver.findElement(By.id("UserLoginForm_password")).click();
    driver.findElement(By.id("UserLoginForm_password")).click();
    
    driver.findElement(By.cssSelector(".btn-new")).click();
    driver.findElement(By.linkText("Check In")).click();
    Thread.sleep(5000);
    driver.findElement(By.xpath("//*[@id=\"ticketCheckin\"]/div[2]/div/a[1]/div")).click();
    Thread.sleep(5000);
    driver.findElement(By.xpath("//*[@id=\"appointmentModal\"]/div[3]/a")).click();
    Thread.sleep(5000);
    driver.findElement(By.linkText("+")).click();
    Thread.sleep(5000);
    driver.findElement(By.id("apt_customer")).click();
    driver.findElement(By.id("apt_customer")).sendKeys("lucas");
    Thread.sleep(10000);
    driver.findElement(By.id("apt_customer")).click();
    driver.findElement(By.id("apt_customer")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("apt_customer")).sendKeys("lucas");
    driver.findElement(By.id("apt_customer")).sendKeys(Keys.ENTER);
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".add-on > .icon-calendar")).click();
    driver.findElement(By.linkText("24")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".btn-save")).click();
    Thread.sleep(5000);
    
    driver.quit();
  }
  }
  
