package batteriesplus;

// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class NewAppointment {

	@Test
	public void newAppointmentChrome() throws InterruptedException {
		newappointment(new ChromeDriver());
	}
	
	public void newAppointmentFirefox() throws InterruptedException {
		newappointment(new FirefoxDriver());
	}
	
	public void newAppointmentIE() throws InterruptedException {
		newappointment(new InternetExplorerDriver());
	}

	private void newappointment(WebDriver driver) throws InterruptedException {
		try {
			driver.get("https://batteriesplus-uat.repairq.io/site/login");
			driver.manage().window().setSize(new Dimension(1176, 743));

			WebElement usernameField = driver.findElement(By.id("UserLoginForm_username"));
			usernameField.click();
			usernameField.clear();
			usernameField.sendKeys("l.costa@cinq.com.br");

			WebElement passwordField = driver.findElement(By.id("UserLoginForm_password"));
			passwordField.click();
			passwordField.clear();
			passwordField.sendKeys("123");

			driver.findElement(By.id("UserLoginForm_password")).click();
			driver.findElement(By.id("UserLoginForm_password")).click();

			driver.findElement(By.cssSelector(".btn-new")).click();
			driver.findElement(By.linkText("Check In")).click();

			WebElement btnAppointments = new WebDriverWait(driver, 5).until(ExpectedConditions
					.elementToBeClickable(By.cssSelector("#ticketCheckin [href='#appointmentModal']")));

			btnAppointments.click();

			WebElement btnViewAllApointments = new WebDriverWait(driver, 5).until(
					ExpectedConditions.elementToBeClickable(By.cssSelector("#appointmentModal [href='/appointment']")));

			btnViewAllApointments.click();
			
			/* Checking validation of a past date */
			createAppointment(driver, "27");
			// TODO Set yesterday date to check validation
			
			Thread.sleep(2000);
			driver.findElement(By.cssSelector("#appointment-edit-modal .close")).click();
			
			// TODO Set the current date
			/*  */
			createAppointment(driver, "28");
			createAppointment(driver, "28");
			createAppointment(driver, "28");

		} finally {
			driver.quit();
		}
	}
	
	private void createAppointment(WebDriver driver, String day) throws InterruptedException {
		Thread.sleep(5000);
		driver.findElement(By.cssSelector(".appointment-create")).click();
		
		Thread.sleep(5000);
		driver.findElement(By.id("apt_customer")).click();
		driver.findElement(By.id("apt_customer")).sendKeys("lucas");
		Thread.sleep(10000);
		driver.findElement(By.id("apt_customer")).click();
		driver.findElement(By.id("apt_customer")).sendKeys(Keys.DOWN);
		driver.findElement(By.id("apt_customer")).sendKeys("lucas");
		driver.findElement(By.id("apt_customer")).sendKeys(Keys.ENTER);
		Thread.sleep(5000);
		driver.findElement(By.cssSelector(".add-on > .icon-calendar")).click();
		
		driver.findElement(By.linkText(day)).click();
		driver.findElement(By.cssSelector(".btn-save")).click();
	}
}