package batteriesplus;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.openqa.selenium.SearchContext;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class SquareTrade {

	
	
	public void SquareTradeChrome() throws InterruptedException {
		checkinSquareTrade(new ChromeDriver());
	}

	public void SquareTradeFirefox() throws InterruptedException {
		checkinSquareTrade(new FirefoxDriver());
	}

	public void SquareTradeIE() throws InterruptedException {
		checkinSquareTrade(new InternetExplorerDriver());
	}

	// Testing Error ( Customer Declined )

	@Test
	public void SquareErrorChrome() throws InterruptedException {
		SquareError(new ChromeDriver());

	}

	public void SquareErrorFirefox() throws InterruptedException {
		SquareError(new FirefoxDriver());

	}

	public void SquareErrorIE() throws InterruptedException {
		SquareError(new InternetExplorerDriver());

	}

	private void checkinWithSquareTrade(WebDriver driver) throws InterruptedException {

		driver.get("https://batteriesplus-uat.repairq.io/site/login");
		driver.manage().window().setSize(new Dimension(1176, 743));

		WebElement usernameField = driver.findElement(By.id("UserLoginForm_username"));
		usernameField.click();
		usernameField.clear();
		usernameField.sendKeys("l.costa@cinq.com.br");

		WebElement passwordField = driver.findElement(By.id("UserLoginForm_password"));
		passwordField.click();
		passwordField.clear();
		passwordField.sendKeys("123");

		driver.findElement(By.id("UserLoginForm_password")).click();
		driver.findElement(By.id("UserLoginForm_password")).click();
		driver.findElement(By.cssSelector(".btn-new")).click();

		Thread.sleep(2000);
		driver.findElement(By.linkText("Check In")).click();
		
		
		WebElement btnCheckinNewModal = new WebDriverWait(driver, 5).until(ExpectedConditions
				.elementToBeClickable(By.cssSelector("#ticketCheckin [href='#ticketCheckinNewModal']")));

		btnCheckinNewModal.click();
		
		
		WebElement btnAssurant = new WebDriverWait(driver, 5).until(ExpectedConditions
				.elementToBeClickable(By.cssSelector("#serviceAuthorizers [data-integrated-name='squaretrade']")));

		btnAssurant.click();
		
				
	
		Thread.sleep(1000);
		
		driver.findElement(By.id("claimNumber")).click();
		driver.findElement(By.id("claimNumber")).sendKeys("stub_lucas218");
		driver.findElement(By.cssSelector(".claim-number-submit:nth-child(3)")).click();
		
			
		
		
		WebElement btnContact = new WebDriverWait(driver, 5).until(ExpectedConditions
				.elementToBeClickable(By.cssSelector("#claimPreviewModal [href^='/ticket/edit/']")));

		btnContact.click();
		
			
	}

	private void checkinSquareTrade(WebDriver driver) throws InterruptedException {
		JavascriptExecutor js = (JavascriptExecutor) driver;

		try {

			checkinWithSquareTrade(driver);
			
			WebElement btnYes = new WebDriverWait(driver, 10)
					.until(ExpectedConditions.elementToBeClickable(By.linkText("Yes")));

			btnYes.click();
			
			
			WebElement btnContinueClaim = new WebDriverWait(driver, 10)
					.until(ExpectedConditions.elementToBeClickable(By.linkText("Continue with Claim")));

			btnContinueClaim.click();
			
				
	
			Thread.sleep(2000);
			
			driver.findElement(By.cssSelector(".check")).click();
			
			
			WebElement btnContinue = new WebDriverWait(driver, 10)
					.until(ExpectedConditions.elementToBeClickable(By.linkText("Continue")));

			btnContinue.click();
			
			
			WebElement btnSamsung = new WebDriverWait(driver, 10).until(
					ExpectedConditions.elementToBeClickable(By.cssSelector("#new-device-form [data-category-id='452']")));

			btnSamsung.click();

			WebElement btnS9 = new WebDriverWait(driver, 10).until(ExpectedConditions
					.elementToBeClickable(By.cssSelector("#new-device-form [data-catalogitem-id='10006']")));
			
			btnS9.click();
			
			
			WebElement btnContinueClaim1 = new WebDriverWait(driver, 10)
					.until(ExpectedConditions.elementToBeClickable(By.linkText("Continue with Claim")));

			btnContinueClaim1.click();
			
						
			
			driver.switchTo().frame(0);
			driver.findElement(By.cssSelector("p")).click();
			{
				WebElement element = driver.findElement(By.id("tinymce"));
				js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'testing'}",
						element);
			}
			driver.switchTo().defaultContent();
			
			
			WebElement btnContinueClaim2 = new WebDriverWait(driver, 10)
					.until(ExpectedConditions.elementToBeClickable(By.linkText("Continue with Claim")));

			btnContinueClaim2.click();
			
			
			WebElement btnSaveSubmit = new WebDriverWait(driver, 10)
					.until(ExpectedConditions.elementToBeClickable(By.linkText("Save & Submit")));

			btnSaveSubmit.click();
			
			
			WebElement btnName = new WebDriverWait(driver, 10)
					.until(ExpectedConditions.elementToBeClickable(By.name("87")));

			btnName.click();
			
				
			
			driver.findElement(By.cssSelector(".control-group:nth-child(4) .radio-inline:nth-child(2) > .required"))
					.click();
			driver.findElement(By.cssSelector(".control-group:nth-child(6) .radio-inline:nth-child(2) > .required"))
					.click();
			driver.findElement(By.cssSelector(".control-group:nth-child(10) .radio-inline:nth-child(2) > .required"))
					.click();
			driver.findElement(By.name("42")).click();
			driver.findElement(By.name("43")).click();
			driver.findElement(By.cssSelector(".control-group:nth-child(17) .radio-inline:nth-child(3) > .required"))
					.click();
			driver.findElement(By.cssSelector(".control-group:nth-child(19) .radio-inline:nth-child(2) > .required"))
					.click();
			driver.findElement(By.cssSelector(".control-group:nth-child(21) .radio-inline:nth-child(2) > .required"))
					.click();
			driver.findElement(By.cssSelector(".control-group:nth-child(23) .radio-inline:nth-child(2) > .required"))
					.click();
			driver.findElement(By.name("76")).click();
			driver.findElement(By.cssSelector(".control-group:nth-child(30) .radio-inline:nth-child(2) > .required"))
					.click();
			driver.findElement(By.cssSelector(".control-group:nth-child(33) .radio-inline:nth-child(3)")).click();
			driver.findElement(By.name("61")).click();
			driver.findElement(By.id("customField_62")).click();
			driver.findElement(By.id("customField_62")).sendKeys("123");
			driver.findElement(By.cssSelector(".control-group:nth-child(38) .radio-inline:nth-child(2) > .required"))
					.click();
			driver.findElement(By.cssSelector(".control-group:nth-child(41) .radio-inline:nth-child(2)")).click();
			driver.findElement(By.cssSelector(".control-group:nth-child(42) .radio-inline:nth-child(2) > .required"))
					.click();
			driver.findElement(By.cssSelector(".control-group:nth-child(43) .radio-inline:nth-child(2) > .required"))
					.click();
			driver.findElement(By.cssSelector(".control-group:nth-child(45) .radio-inline:nth-child(2) > .required"))
					.click();
			driver.findElement(By.cssSelector(".control-group:nth-child(46) .radio-inline:nth-child(3) > .required"))
					.click();
			driver.findElement(By.cssSelector(".control-group:nth-child(47) .radio-inline:nth-child(3) > .required"))
					.click();
			
			
			driver.findElement(By.id("customField_80")).click();
			driver.findElement(By.id("customField_80")).sendKeys("complete");
			
			
			
			WebElement btnSaveSubmit1 = new WebDriverWait(driver, 10)
					.until(ExpectedConditions.elementToBeClickable(By.linkText("Save & Submit")));

			btnSaveSubmit1.click();
			
			
			
			WebElement btnaddBtn = new WebDriverWait(driver, 10)
					.until(ExpectedConditions.elementToBeClickable(By.id("addBtn")));

			btnaddBtn.click();
			
			
			WebElement btnRepair = new WebDriverWait(driver, 10).until(ExpectedConditions
					.elementToBeClickable(By.cssSelector("#ticket-item-form [data-catalogitem-id='34438']")));

			btnRepair.click();

			WebElement btnbtnlarge = new WebDriverWait(driver, 10)
					.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-large")));

			btnbtnlarge.click();

			WebElement btnCreateEstimate = new WebDriverWait(driver, 10)
					.until(ExpectedConditions.elementToBeClickable(By.linkText("Create Estimate")));

			btnCreateEstimate.click();
			
									
			
			WebElement btnStartRepair = new WebDriverWait(driver, 10)
					.until(ExpectedConditions.elementToBeClickable(By.linkText("Start Repair")));

			btnStartRepair.click();

			WebElement btnRepairComplete = new WebDriverWait(driver, 10)
					.until(ExpectedConditions.elementToBeClickable(By.linkText("Repair Complete")));

			btnRepairComplete.click();
			
			Thread.sleep(6000);
			
			
			driver.findElement(By.id("claim-contact-notify-note")).click();
			driver.findElement(By.id("claim-contact-notify-note")).sendKeys("12");
			
			
			WebElement btnContact = new WebDriverWait(driver, 10)
					.until(ExpectedConditions.elementToBeClickable(By.linkText("Contact Notified")));

			btnContact.click();
			
			
			
			Thread.sleep(10000);
			driver.findElement(By.xpath("//*[@id=\"claim\"]/div[2]/div[1]/div[4]/a")).click();
			Thread.sleep(3000);
			driver.findElement(By.linkText("Send to RMS")).click();


		


		} finally {
			driver.quit();

		}

	}

	private void SquareError(WebDriver driver) throws InterruptedException {

		checkinWithSquareTrade(driver);

		driver.findElement(By.linkText("No Match")).click();
		driver.findElement(By.cssSelector(".trigger-claim-decline:nth-child(2)")).click();
		driver.findElement(By.name("claimCannotRepairReason")).click();
		{
			WebElement dropdown = driver.findElement(By.name("claimCannotRepairReason"));
			dropdown.findElement(By.xpath("//option[. = 'Customer Declined Due to Price']")).click();
		}
		driver.findElement(By.name("claimCannotRepairReason")).click();
		driver.findElement(By.linkText("Cancel Claim")).click();
	}

}
